perf(derive): Prevent duplicate batch validity checks
anton-rs/kona pull request #353
Opened 2024-06-29 20:22 UTC by clabby

## Overview

Prevents duplicate batch validity checks by caching the result of the first check in the `BatchWithInclusionBlock` type. If the validity has already been determined, it will be returned immediately rather than repeating the work.

2024-06-29 20:22 UTC, clabby commented
* **#353** <a href="https://app.graphite.dev/github/pr/ethereum-optimism/kona/353?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @clabby and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-07-08 13:57 UTC, refcell approved these changes
I don't think this should have any repercussions from re-orgs or following tip more generally - though would be good to validate this.

2024-07-08 21:15 UTC, clabby commented
We will not be including this in our first release for the upcoming alpha deployment. Please do not merge this PR just yet.

Waiting on https://github.com/ethereum-optimism/optimism/pull/11055

2024-08-12 00:59 UTC, refcell requested changes
Requesting changes so we don't accidentally merge this

2024-10-19 14:02 UTC, closed without merging