feat: add latest block number to chain provider for op-rs
anton-rs/kona pull request #521
Opened 2024-09-09 22:35 UTC by refcell

2024-09-09 22:35 UTC, refcell commented
* **#521** <a href="https://app.graphite.dev/github/pr/anton-rs/kona/521?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @refcell and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-09-22 18:25 UTC, clabby requested changes

2024-09-22 18:25 UTC, clabby commented on crates/derive/src/online/alloy_providers.rs
> +            self.inner.raw_request("eth_blockNumber".into(), ()).await;
I believe there's a function for this on the provider itself, yeah? [`Provider::get_block_number`](https://docs.rs/alloy-provider/latest/alloy_provider/trait.Provider.html#method.get_block_number)

2024-09-23 15:37 UTC, clabby approved these changes

2024-09-23 15:41 UTC, merged