feat: remove attributes
anton-rs/kona pull request #529
Opened 2024-09-16 20:19 UTC by refcell

2024-09-16 20:19 UTC, refcell commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/anton-rs/kona/529?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#529** <a href="https://app.graphite.dev/github/pr/anton-rs/kona/529?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#528** <a href="https://app.graphite.dev/github/pr/anton-rs/kona/528?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @refcell and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-09-16 20:28 UTC, refcell commented on Cargo.lock
> +]
Unfortunately, this is why the build on cannon is failing. `alloy-serde` is not currently hidden behind the `serde` feature flag so it leaks serde and std features into the `no_std` environment.

2024-09-16 20:29 UTC, refcell commented on Cargo.lock
> +]
The issue is in upstream `alloy-rpc-types-engine` as well. Working on fixing this in pr https://github.com/alloy-rs/alloy/pull/1284

2024-09-16 20:51 UTC, clabby requested changes
Looks good, but I'd prefer if we changed `OptimismPayloadAttributes` to not have `Option`s for `transactions`, `no_tx_pool`. These should always be there, since the type is not intended to be backwards-compat w/ L1 payload attributes.

2024-09-16 20:51 UTC, clabby commented on crates/derive/src/stages/attributes_queue.rs
> +        attributes.no_tx_pool = Some(true);
Why is this an option in `OptimismPayloadAttributes`? Should always be there, doesn't have to be backwards compat w/ L1.

2024-09-16 20:51 UTC, clabby commented on crates/derive/src/stages/attributes_queue.rs
> +        }
same same - why is this an option?

2024-09-16 23:14 UTC, refcell commented
> Looks good, but I'd prefer if we changed `OptimismPayloadAttributes` to not have `Option`s for `transactions`, `no_tx_pool`. These should always be there, since the type is not intended to be backwards-compat w/ L1 payload attributes.

They're all marked `omitempty` in the reference implementation: https://github.com/ethereum-optimism/optimism/blob/8dd6fb36aad7a1cd5c9e7e877b340b2e0c5cc14c/op-service/eth/types.go#L326-L331

Do you want to diverge from this for any specific reason?

2024-09-17 14:52 UTC, clabby approved these changes

2024-09-17 15:17 UTC, merged